#######################################
# Environment Configuration
#  - feel free to edit -
# -> for most changes you only have to
#         docker-compose up -d
#    to apply them
#######################################

#######################################
# Webserver

# General
WEB_DOCUMENT_ROOT=/app/
WEB_DOCUMENT_INDEX=index.php
CLI_SCRIPT=php /app/index.php

#######################################
# PHP settings
# (available in docker images after 2017-06-15)

# PHP.ini

# php.memory_limit=2G
# php.date.timezone=UTC
# php.display_errors=1
# php.max_execution_time=600
# php.post_max_size=50M
# php.upload_max_filesize=50M

# FPM global (master)

# fpm.global.process_control_timeout=5m
# fpm.global.process.max=100

# FPM pool

# fpm.pool.pm=dynamic
# fpm.pool.pm.max_children=20
# fpm.pool.pm.start_servers=20
# fpm.pool.pm.min_spare_servers=1
# fpm.pool.pm.max_spare_servers=3
# fpm.pool.pm.process_idle_timeout=10s
# fpm.pool.pm.max_requests=1000
# fpm.pool.request_terminate_timeout=5m

#######################################
# SSH settings
# SSH public key (without comment):
# -> ssh-rsa AAAAB3Nza....
#  Github public ssh keys:
# -> https://github.com/USERNAME.keys
SSH_AUTH_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCwjoOUWnw9+JoPmE0cXaNtesLLJNN+VVawRX91ViHjpt95G7Id4gKz1H8w3iK+Ja1ms2F+sLZ3zmbObX1V1GjD0wgmymdCTFehygdwA/Sao+in9kb3tzms4VLiI4WXDMoXx/6tVXlLYiW73osr8nN2s6ZS2gqeBk0ZXwu7fTHiUJsSnkkvcCIVTimzv/xjGnDNfUiyDDuSHuFDVANrbPZgmXD0E9nwMog5eTcW8BKHAtW9Q4ouCcNyxV7+eHYz5EPbhOtEDoBA6Zs6u44zBlWI27YajLYXlpAlVoJRx7gweVY4p4aTtaAKHRMScFuLvx6YS8azNFe3S3P8OHSC32Wmn8XeKwq7OAZSn+GHl/MONEYeSEt45mDqiufUhNTZIa6m9elpBMh3K2IJtfThqiKSnEi1KMQdoar/x0xVW+yHFzNe+RRrLxvxuo5uLgBThuE2G/6tPmTqwsdGM2Mtz5kYgl7SJP7CSjHHK+i/+AoJKJMa4ggvqMsh20cvUnWHk407dglXLkA9D2yF+1b5Xsn8jHaHweulUHUK2nhdEfVF1otwIO4GOApUQF9g6ngiR4nsEwfmH4iuo2R+facI6BJSuohbMiV4R9PPNUkIEZMFRlTiYquPGvZ/CqoQxVQBhl78GCpwTBbLmQZYSh5G49fiVF3qS8A41jdQaCbusCXPqw== fm@fellek.net"

#######################################
# MySQL settings
# -> if you change these settings
#    you have to remove the database:
#         docker-compose rm mysql
#    because it's stored database in
#    volume and provisioning is only
#    done once.
MYSQL_ROOT_PASSWORD=dev
MYSQL_USER=dev
MYSQL_PASSWORD=dev
MYSQL_DATABASE=database

#######################################
# PostgreSQL settings
POSTGRES_USER=dev
POSTGRES_PASSWORD=dev
POSTGRES_DATABASE=dev

#######################################
# FTP settings
FTP_USER=dev
FTP_PASSWORD=dev
FTP_UID=1000
FTP_GID=1000
FTP_PATH=/storage/ftp/
#FTP_PATH=/app/
